services:
  - type: web
    name: flowdraw-client
    env: node
    buildCommand: npm run build
    startCommand: npm run start
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18